In [2]:
from sklearn import datasets
import pandas as pd
import numpy as np


In [6]:
data = pd.read_csv("datasets/ChurnData.csv")
data.corr()

tenure       age   address    income        ed    employ  \
tenure    1.000000  0.431802  0.456328  0.109383 -0.070503  0.445755   
age       0.431802  1.000000  0.746566  0.211275 -0.071509  0.622553   
address   0.456328  0.746566  1.000000  0.132807 -0.145550  0.520926   
income    0.109383  0.211275  0.132807  1.000000  0.141241  0.345161   
ed       -0.070503 -0.071509 -0.145550  0.141241  1.000000 -0.213886   
employ    0.445755  0.622553  0.520926  0.345161 -0.213886  1.000000   
equip    -0.117102 -0.071357 -0.148977 -0.010741  0.488041 -0.174470   
callcard  0.426530  0.170404  0.209204 -0.019969 -0.071178  0.266612   
wireless -0.070590 -0.065527 -0.146478 -0.029635  0.267670 -0.101187   
longmon   0.763134  0.373547  0.421782  0.041808 -0.072735  0.363386   
tollmon   0.100214  0.053595 -0.015564 -0.003701 -0.000712  0.117962   
equipmon -0.043274 -0.030402 -0.125212  0.000275  0.492999 -0.141651   
cardmon   0.489857  0.203202  0.297395 -0.013513 -0.070990  0.219413   
wiremon   0.043067 -0.003685 -0.113143 -0.027998  0.288571 -0.045539   
longten   0.796355  0.393370  0.447256  0.048374 -0.083032  0.385254   
tollten   0.398869  0.187221  0.129141 -0.000262 -0.016257  0.240498   
cardten   0.676920  0.336903  0.406964  0.019358 -0.069499  0.309183   
voice    -0.050686  0.019555 -0.069627  0.085525  0.233628 -0.035922   
pager     0.018791  0.006803 -0.105812  0.056977  0.258698  0.038381   
internet -0.164921 -0.078395 -0.191058  0.102809  0.552996 -0.250044   
callwait -0.009747  0.020002 -0.019967  0.081133 -0.016247  0.119708   
confer    0.080650  0.030625 -0.030494 -0.031556 -0.132215  0.173247   
ebill    -0.099128 -0.048279 -0.172171 -0.041392  0.427315 -0.151965   
loglong   0.864388  0.379413  0.409357  0.065595 -0.054581  0.377186   
logtoll   0.310045  0.093600  0.018386 -0.156498 -0.007227  0.068718   
lninc     0.246353  0.313359  0.212929  0.680313  0.206718  0.540052   
custcat   0.134237  0.041055 -0.016841  0.030725  0.013127  0.131292   
churn    -0.376860 -0.287697 -0.260659 -0.090790  0.216112 -0.337969   

             equip  callcard  wireless   longmon  ...     pager  internet  \
tenure   -0.117102  0.426530 -0.070590  0.763134  ...  0.018791 -0.164921   
age      -0.071357  0.170404 -0.065527  0.373547  ...  0.006803 -0.078395   
address  -0.148977  0.209204 -0.146478  0.421782  ... -0.105812 -0.191058   
income   -0.010741 -0.019969 -0.029635  0.041808  ...  0.056977  0.102809   
ed        0.488041 -0.071178  0.267670 -0.072735  ...  0.258698  0.552996   
employ   -0.174470  0.266612 -0.101187  0.363386  ...  0.038381 -0.250044   
equip     1.000000 -0.087051  0.386735 -0.097618  ...  0.308633  0.623509   
callcard -0.087051  1.000000  0.220118  0.322514  ...  0.251069 -0.067146   
wireless  0.386735  0.220118  1.000000 -0.073043  ...  0.667535  0.343631   
longmon  -0.097618  0.322514 -0.073043  1.000000  ... -0.001372 -0.223929   
tollmon  -0.090516  0.352994  0.462751  0.083771  ...  0.499124  0.036393   
equipmon  0.941065  0.026955  0.527573 -0.070876  ...  0.461458  0.631338   
cardmon  -0.056590  0.629955  0.195387  0.493439  ...  0.216653 -0.129166   
wiremon   0.367579  0.259638  0.885879 -0.020392  ...  0.704724  0.359273   
longten  -0.098271  0.342553 -0.088461  0.984808  ... -0.011369 -0.217916   
tollten  -0.097151  0.292555  0.328256  0.338036  ...  0.390620 -0.017063   
cardten  -0.053837  0.448182  0.047773  0.673179  ...  0.097579 -0.154030   
voice     0.264481  0.226109  0.649721 -0.080503  ...  0.608335  0.243845   
pager     0.308633  0.251069  0.667535 -0.001372  ...  1.000000  0.266193   
internet  0.623509 -0.067146  0.343631 -0.223929  ...  0.266193  1.000000   
callwait -0.034021  0.370878  0.389670  0.032913  ...  0.426690  0.019419   
confer   -0.103499  0.311056  0.382925  0.060614  ...  0.352743 -0.029911   
ebill     0.603133 -0.045058  0.321433 -0.124605  ...  0.288752  0.512987   
loglong  -0.113065  0.351030 -0.042637  0.901631  ...  0.015771 -0.202230  

In [92]:
x = data[["tenure","employ" ]]

In [93]:
y = data[["churn"]]

In [94]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
x_train, x_test, y_train, y_test


(     tenure  employ
 87     65.0    26.0
 78     69.0    19.0
 117    11.0     3.0
 41     53.0     7.0
 144    45.0     2.0
 ..      ...     ...
 97     25.0    33.0
 146     6.0     5.0
 155    53.0     2.0
 183    51.0    16.0
 140     8.0    17.0
 
 [160 rows x 2 columns],      tenure  employ
 69     72.0    20.0
 159    10.0     0.0
 61     60.0    11.0
 152    17.0    10.0
 3      38.0    10.0
 101    20.0     5.0
 67     61.0    13.0
 42     50.0    16.0
 39     43.0    18.0
 162    60.0    11.0
 20     35.0    11.0
 141    66.0     4.0
 34     18.0     8.0
 130    72.0    44.0
 194    57.0    27.0
 73     52.0     8.0
 160    21.0     1.0
 47     37.0    12.0
 7       9.0     2.0
 14     16.0     5.0
 1      33.0     0.0
 165    18.0    14.0
 102    34.0     0.0
 143    63.0     9.0
 199    61.0    22.0
 51     26.0     9.0
 120     4.0     2.0
 182    32.0    24.0
 33     33.0     4.0
 167     7.0     4.0
 27     57.0     9.0
 118    23.0     8.0
 122    24.0     6.0
 138    

# SVM

In [95]:
from sklearn.svm import SVC

In [103]:
clf = SVC(kernel='rbf').fit(x_train, y_train)

C:\Users\mukes\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\mukes\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [104]:
y_hat = clf.predict(x_test)


In [105]:
from sklearn.metrics import confusion_matrix
cnf = confusion_matrix(y_hat, y_test)
cnf

array([[27,  8],
       [ 4,  1]], dtype=int64)

In [107]:
cnf[0][0]+cnf[1][1]

27

In [100]:
(31+0)/(31+9+0+0)

0.775

# Decision Tree

In [108]:
from sklearn.tree import DecisionTreeClassifier
obj = DecisionTreeClassifier(criterion="entropy")
obj = obj.fit(x_train,y_train)
obj_y_hat = obj.predict(x_test)

In [109]:
obj_cnf = confusion_matrix(obj_y_hat, y_test)

In [112]:
obj_cnf


array([[22,  2],
       [ 9,  7]], dtype=int64)

In [113]:
(22+7)/(22+2+7+9)

0.725

# Logistic Regression

In [116]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(max_iter = 500).fit(x_train,y_train)
yhat_prob = LR.predict(x_test)
yhat_prob

C:\Users\mukes\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\mukes\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0.])

In [122]:
lr_cnf = confusion_matrix(yhat_prob, y_test)
lr_cnf

array([[29,  6],
       [ 2,  3]], dtype=int64)

In [123]:
(29+3)/(29+3+6+2)

0.8

# KNN

In [146]:
from sklearn.neighbors import KNeighborsClassifier
k = 4
neigh = KNeighborsClassifier(n_neighbors = k).fit(x_train,y_train)
neigh
knn_yhat = neigh.predict(x_test)

C:\Users\mukes\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


In [147]:
from sklearn import metrics
print("Train set Accuracy: ", metrics.accuracy_score(y_train, neigh.predict(x_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, knn_yhat))

Train set Accuracy:  0.825
Test set Accuracy:  0.75
