In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
%matplotlib inline 
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("ChurnData.csv")
df.head()

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   

   longmon  ...  pager  internet  callwait  confer  ebill  loglong  logtoll  \
0     4.40  ...    1.0       0.0       1.0     1.0    0.0    1.482    3.033   
1     9.45  ...    0.0       0.0       0.0     0.0    0.0    2.246    3.240   
2     6.30  ...    0.0       0.0       0.0     1.0    0.0    1.841    3.240   
3     6.05  ...    1.0       1.0       1.0     1.0    1.0    1.800    3.807   
4     7.10  ...    0.0       0.0       1.0     1.0    0.0    1.960    3.091   

   lninc  custcat  churn  
0  4.913      4.0    1.0  
1  3.497      1.0    1.0  
2  3.401      3.0    0.0  
3  4.331      4.0    0.0  
4  4.382      3.0    0.0  

[5 rows x 28 columns]

In [4]:
df = df[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip',   'callcard', 'wireless','churn']]
df['churn'] =df['churn'].astype('int')
df.head()

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   

   churn  
0      1  
1      1  
2      0  
3      0  
4      0

In [7]:
x=df[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip']]

In [8]:
x

tenure   age  address  income   ed  employ  equip
0      11.0  33.0      7.0   136.0  5.0     5.0    0.0
1      33.0  33.0     12.0    33.0  2.0     0.0    0.0
2      23.0  30.0      9.0    30.0  1.0     2.0    0.0
3      38.0  35.0      5.0    76.0  2.0    10.0    1.0
4       7.0  35.0     14.0    80.0  2.0    15.0    0.0
..      ...   ...      ...     ...  ...     ...    ...
195    55.0  44.0     24.0    83.0  1.0    23.0    0.0
196    34.0  23.0      3.0    24.0  1.0     7.0    0.0
197     6.0  32.0     10.0    47.0  1.0    10.0    0.0
198    24.0  30.0      0.0    25.0  4.0     5.0    0.0
199    61.0  50.0     16.0   190.0  2.0    22.0    1.0

[200 rows x 7 columns]

In [9]:
y =df['churn']

In [10]:
y

0      1
1      1
2      0
3      0
4      0
      ..
195    0
196    0
197    0
198    1
199    0
Name: churn, Length: 200, dtype: int32

In [14]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
x_train, x_test, y_train, y_test


(     tenure   age  address  income   ed  employ  equip
 1      33.0  33.0     12.0    33.0  2.0     0.0    0.0
 125    72.0  75.0     48.0    14.0  2.0     6.0    0.0
 77     10.0  34.0      1.0    52.0  5.0     3.0    1.0
 32     22.0  34.0      1.0    46.0  3.0     1.0    1.0
 28      3.0  24.0      2.0    20.0  2.0     3.0    0.0
 ..      ...   ...      ...     ...  ...     ...    ...
 58     32.0  27.0      3.0    91.0  4.0     1.0    1.0
 108    32.0  34.0      0.0    38.0  1.0    10.0    0.0
 152    17.0  39.0     12.0    45.0  4.0    10.0    1.0
 135    72.0  62.0     35.0   163.0  5.0    31.0    1.0
 49     58.0  58.0     10.0    96.0  2.0    17.0    0.0
 
 [160 rows x 7 columns],      tenure   age  address  income   ed  employ  equip
 143    63.0  37.0      1.0    45.0  4.0     9.0    1.0
 121    10.0  28.0      9.0    75.0  4.0     1.0    1.0
 21     13.0  54.0      2.0    31.0  4.0     2.0    0.0
 84     26.0  30.0      9.0    18.0  4.0     1.0    0.0
 101    20.0  32.0    

In [15]:
from sklearn.svm import SVC

In [16]:
clf = SVC(kernel='rbf').fit(x_train, y_train)

D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [18]:
y_hat = clf.predict(x_test)
y_hat

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
from sklearn.metrics import confusion_matrix
cnf = confusion_matrix(y_hat, y_test)
cnf

array([[30, 10],
       [ 0,  0]], dtype=int64)

In [20]:
cnf[0][0]+cnf[1][1]

30

In [21]:
(31+0)/(31+9+0+0)

0.775

# Descision Tree

In [22]:
from sklearn.tree import DecisionTreeClassifier
obj = DecisionTreeClassifier(criterion="entropy")
obj = obj.fit(x_train,y_train)
obj_y_hat = obj.predict(x_test)

In [23]:
obj_cnf = confusion_matrix(obj_y_hat, y_test)

In [24]:
obj_cnf


array([[18,  4],
       [12,  6]], dtype=int64)

In [25]:
(22+7)/(22+2+7+9)

0.725

In [26]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(max_iter = 500).fit(x_train,y_train)
yhat_prob = LR.predict(x_test)
yhat_prob

D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1])

In [27]:
lr_cnf = confusion_matrix(yhat_prob, y_test)
lr_cnf

array([[23,  5],
       [ 7,  5]], dtype=int64)

In [28]:
(29+3)/(29+3+6+2)

0.8