In [1]:
import numpy as np

In [3]:
a=[1,2,3]
b=np.array(a)
print(a)
print(b)
print(type(b))

[1, 2, 3]
[1 2 3]
<class 'numpy.ndarray'>


In [5]:
a=[1,2,3,'5',4.0]
b=np.array(a,dtype='int')
print(b)

[1 2 3 5 4]


In [6]:
a=[1,2,3,'5',4.0]
b=np.array(a*3)
print(b)

['1' '2' '3' '5' '4.0' '1' '2' '3' '5' '4.0' '1' '2' '3' '5' '4.0']


In [9]:
ones=np.ones(3,dtype=int)
ones

array([1, 1, 1])

In [10]:
zeros=np.zeros(3,dtype=int)
zeros

array([0, 0, 0])

In [15]:
#2D array
ones2d=np.ones((2,3),dtype=int)
ones2d

array([[1, 1, 1],
       [1, 1, 1]])

In [16]:
b=np.zeros((3,4),dtype=int)
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [18]:
b=np.full((3,2),5)
b

array([[5, 5],
       [5, 5],
       [5, 5]])

In [28]:
c=np.empty(20)
c

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 1.29060871e-306,
       2.11397635e-307, 1.33511562e-306, 1.11258989e-306, 1.69118787e-306,
       1.42420617e-306, 1.60219035e-306, 1.78020984e-306, 1.37962117e-306,
       1.11257767e-306, 1.06811422e-306, 1.11256749e-306, 1.78021798e-306,
       8.06612616e-308, 9.34566331e-307, 8.90098806e-307, 1.22387635e-307])

In [29]:
import numpy as np

a=[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
ans=np.array(a)
print(ans)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
ans=np.array([0,0,0,0,1,0,0,0,0,0])
for i in ans:
    print(i,end=' ')

0 0 0 0 1 0 0 0 0 0 

In [35]:
ans=np.zeros(10,dtype=int)
ans[4]=1
for i in ans:
    print(i,end=' ')

0 0 0 0 1 0 0 0 0 0 

# Method

In [37]:
#arange
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
a=np.arange(2,21,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [55]:
#linspace
b=np.linspace(2,10)
b

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [44]:
print(b[1]-b[0])
print(b[3]-b[2])

0.16326530612244916
0.16326530612244916


In [47]:
b=np.linspace(2,20,10,dtype=int)
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [50]:
b=np.linspace(2,10,5,dtype=int,endpoint=False)
b

array([2, 3, 5, 6, 8])

In [57]:
b=np.linspace(2,10,5,dtype=int,endpoint=False,retstep=True)
b

(array([2, 3, 5, 6, 8]), 1.6)

In [60]:
#identity
b=np.identity(4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [64]:
#eye
b=np.eye(4,4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [67]:
#Random
b=np.random.rand(3,2)
b

array([[0.53331886, 0.88202141],
       [0.75975162, 0.28564136],
       [0.50996755, 0.97445363]])

In [68]:
b=np.random.rand(3)
b

array([0.95121699, 0.88113985, 0.72417701])

In [69]:
b=np.random.rand(3)*10
b

array([1.09933713, 5.0918916 , 3.21805494])

In [80]:
b=np.random.randint(5)
b

3

In [92]:
b=np.random.randint(10,size=(4,4))
b

array([[3, 0, 8, 7],
       [4, 7, 8, 9],
       [9, 5, 0, 1],
       [8, 5, 3, 0]])

In [89]:
a = np.array([0, 1, 2, 3])
a.shape

(4,)

In [90]:
np.random.rand()

0.6564812997574722

In [91]:
y = np.zeros((2, 3, 4))
y

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [93]:
b=np.arange(9,50)
for i in b:
    print(i,end=' ')

9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 

In [97]:
b=np.eye(5,6,dtype=int)
b

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0]])

In [121]:
b=np.linspace(0,5,9)
ans=np.around(b,decimals=2)
for i in ans:
    print(i)

0.0
0.62
1.25
1.88
2.5
3.12
3.75
4.38
5.0


In [122]:
a=5
size=9
ans=a/size
print(ans)

0.5555555555555556


In [133]:
#Show only the cuts point

start     = 0
end       = 5
numPoints = 10 
# **** determine where to cut the rope ****
cuts = np.linspace(start, end, numPoints)
print(cuts)
cuts=cuts[1:-1]
ans=np.around(cuts,decimals=2)
for i in ans:
    print(i)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
0.56
1.11
1.67
2.22
2.78
3.33
3.89
4.44


# Basic Properties of Array

In [129]:
a=[1,2,3,4]
arr=np.array(a)

print(a)
print(arr)

[1, 2, 3, 4]
[1 2 3 4]


In [131]:
print(arr.data)
print(arr.shape)
print(arr.strides)
print(arr.dtype)

(4,)
(4,)
int32


In [134]:
print(arr[1])
print(arr[1:3])

2
[2 3]


In [128]:
a2d=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
arr2d=np.array(a)

print(a2d)
print(arr2d)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [132]:
print(arr2d.data)
print(arr2d.shape)
print(arr2d.strides)
print(arr2d.dtype)

(4, 4)
(16, 4)
int32


In [138]:
print(a2d[1][2])
print(arr2d[1][2])
print(arr2d[1,2])

7
7
7


In [140]:
print(a2d[:3][2])

[9, 10, 11, 12]


In [141]:
print(arr2d[:3,3])

[ 4  8 12]


In [143]:
print(arr2d[3,:4])

[13 14 15 16]


In [145]:
print(arr2d[2:4,1:3])

[[10 11]
 [14 15]]


# Slicing

In [146]:
import numpy as np
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)
print(input_)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [162]:
ans1=input_[2:3,:3]
for i in ans1:
    for j in i:
        print(j,end=' ')

11 12 13 

In [163]:
ans2=input_[1:4,3:4]
for i in ans2:
    for j in i:
        print(j,end=' ')

9 14 19 

In [166]:
ans3=input_[2:4,:]
for i in ans3:
    for j in i:
        print(j,end=' ')

11 12 13 14 15 16 17 18 19 20 

In [167]:
ans4=input_[1:3,1:3]
for i in ans4:
    for j in i:
        print(j,end=' ')

7 8 12 13 

In [168]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)

ans1=input_[2:3,:3]
for i in ans1:
    for j in i:
        print(j,end=' ')
print()        
ans2=input_[1:4,3:4]
for i in ans2:
    for j in i:
        print(j,end=' ')
print()       
ans3=input_[2:4,:]
for i in ans3:
    for j in i:
        print(j,end=' ')
print()        
ans4=input_[1:3,1:3]
for i in ans4:
    for j in i:
        print(j,end=' ')

11 12 13 
9 14 19 
11 12 13 14 15 16 17 18 19 20 
7 8 12 13 

# Mathematical Operation

In [97]:
import numpy as np

li=[1,2,3,4,5]
a=np.random.randint(1,20,5)
b=np.random.randint(1,20,5)

print(li)
print(a)
print(b)

[1, 2, 3, 4, 5]
[1 9 3 9 2]
[ 7 15 14 17 19]


In [4]:
l=[i+1 for i in li]
l

[2, 3, 4, 5, 6]

In [6]:
c=a+b
c

array([16, 14, 33, 18, 27])

In [8]:
d=a-b
d

array([-14,  -2,  -1, -14,  -3])

In [9]:
e=a*b
e

array([ 15,  48, 272,  32, 180])

In [11]:
f=a/b
f

array([0.06666667, 0.75      , 0.94117647, 0.125     , 0.8       ])

In [13]:
g=b//a
g

array([15,  1,  1,  8,  1], dtype=int32)

In [17]:
#Exponent
h=a**b
h

array([          1,     1679616,           0,       65536, -1073741824],
      dtype=int32)

In [18]:
print(a.sum())

37


In [20]:
print(a.mean())

7.4


In [24]:
print(b.min())

8


In [22]:
print(a.max())

16


In [25]:
print(b.argmin())

1


In [26]:
print(a.argmax())

2


# Relational Operation

In [28]:
print(a)
print(b)

[ 1  6 16  2 12]
[15  8 17 16 15]


In [29]:
a>b

array([False, False, False, False, False])

In [30]:
a<b

array([ True,  True,  True,  True,  True])

In [31]:
a==b

array([False, False, False, False, False])

# Logical Operator

In [32]:
print(np.logical_or(a,b))

[ True  True  True  True  True]


In [33]:
print(np.logical_and(a,b))

[ True  True  True  True  True]


In [36]:
print(np.logical_not(a))

[False False False False False]


In [37]:
print(np.logical_not(a,b))

[0 0 0 0 0]


# 2D array

In [39]:
x=np.random.randint(10,size=(3,3))
y=np.random.randint(10,size=(3,3))

In [40]:
print(x)
print(y)

[[5 3 7]
 [7 0 1]
 [6 7 2]]
[[7 9 7]
 [9 1 5]
 [8 1 6]]


In [43]:
add=x+y
add

array([[12, 12, 14],
       [16,  1,  6],
       [14,  8,  8]])

In [44]:
sub=x-y
sub

array([[-2, -6,  0],
       [-2, -1, -4],
       [-2,  6, -4]])

In [45]:
mul=x*y
mul

array([[35, 27, 49],
       [63,  0,  5],
       [48,  7, 12]])

In [47]:
div=x//y
div

array([[0, 0, 1],
       [0, 0, 0],
       [0, 7, 0]], dtype=int32)

In [48]:
print(x.sum())

38


In [49]:
print(x.min())

0


In [50]:
print(x.max())

7


In [51]:
print(y.max())

9


In [55]:
x>=y

array([[False, False,  True],
       [False, False, False],
       [False,  True, False]])

In [54]:
y>=x

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True, False,  True]])

In [56]:
print(np.logical_or(x,y))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [57]:
print(np.logical_and(x,y))

[[ True  True  True]
 [ True False  True]
 [ True  True  True]]


In [58]:
print(np.logical_not(x,y))

[[0 0 0]
 [0 1 0]
 [0 0 0]]


In [59]:
np.logical_xor(x,y)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# Boolean Indexing

In [60]:
print(a)

[ 1  6 16  2 12]


In [61]:
#Find all values which are greater then 5
new_arr=a[a>5]
print(new_arr)

[ 6 16 12]


In [62]:
new=a[(a>5) & (a<15)]
new

array([ 6, 12])

In [64]:
print(x)
c=x
c

[[5 3 7]
 [7 0 1]
 [6 7 2]]


array([[5, 3, 7],
       [7, 0, 1],
       [6, 7, 2]])

In [110]:
print(a)
c=a
c

[1 2 0 0 4 0]


array([1, 2, 0, 0, 4, 0])

In [111]:
c[:2]=11

In [112]:
c

array([11, 11,  0,  0,  4,  0])

In [113]:
c[c>12]=100
c

array([11, 11,  0,  0,  4,  0])

In [114]:
print(x)
print(y)

[[5 3 7]
 [7 0 1]
 [6 7 2]]
[[0 0 0]
 [0 1 0]
 [0 0 0]]


In [115]:
x[1:2,1:2]

array([[0]])

In [116]:
print(a)
print(b)

[11 11  0  0  4  0]
[ 7 15 14 17 19]


In [117]:
ind=np.where(a==11)
print(b[ind])

[ 7 15]


In [106]:
a[a==11]

array([11, 11])

In [118]:
a=np.array([1,2,0,0,4,0])
a

array([1, 2, 0, 0, 4, 0])

In [120]:
x=np.nonzero(a)
x
for i in x:
    print(i)

[0 1 4]


In [95]:
ind=np.where(a!=0)
print(ind)
for i in ind:
    print(i)

(array([0, 1, 4], dtype=int64),)
[0 1 4]


In [129]:
l=[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]
arr=np.array(l)
print(arr)

ind=np.where(arr%3==0)

for i in ind[0]:
    print(i,end=' ')

[ 1  3  5  7  9 11 13 15 17 19]
1 4 7 

In [132]:
l=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
arr=np.array(l)
print(arr)

arr[arr%2!=0]=-1
print(arr)

for i in arr:
    print(i,end=' ')

[ 1  2  3  4  5  6  7  8  9 10]
[-1  2 -1  4 -1  6 -1  8 -1 10]
-1 2 -1 4 -1 6 -1 8 -1 10 

In [136]:
l= [11, 2, 13, 4, 15, 6, 27, 8, 19]
arr=np.array(l)
print(arr)

maxx=arr.max()
print(maxx)

arr[arr==maxx]=0

for i in arr:
    print(i)

[11  2 13  4 15  6 27  8 19]
27
11
2
13
4
15
6
0
8
19


In [142]:
l=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
arr=np.array(l)
print(arr)

arr[(arr>=3) & (arr<=8)]*=-1
for i in arr:
    print(i)

[ 1  2  3  4  5  6  7  8  9 10]
1
2
-3
-4
-5
-6
-7
-8
9
10


In [2]:
age=np.array([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height=np.array([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])

ind=np.where(height>155)
print(ind)
ll=len(ind[0])
print(ll)
ans1=age[ind]
ans2=height[ind]

print(ans1)
print(ans2)

for i in range(ll):
        print(ans1[i],ans2[i])

(array([ 0,  2,  3,  5, 10, 11, 13, 14, 16, 17, 18], dtype=int64),)
11
[15 19 20 21 22 23 16 18 20 15 17]
[156 180 162 157 158 179 182 183 159 160 172]
15 156
19 180
20 162
21 157
22 158
23 179
16 182
18 183
20 159
15 160
17 172


# Boolean Indexing 2D Array

In [55]:
x=np.random.randint(30,size=(5,6))
y=np.random.randint(30,size=(5,6))

In [56]:
print(x)

[[ 2  4 14 12  3 22]
 [ 1  3 10 27 16 17]
 [22 27  6  2  8 11]
 [20 13 21 20 17 18]
 [12  4 26  0 22  9]]


In [13]:
print(y)

[[25  5  8  6  3 25]
 [28 24 21  3 18 14]
 [ 5 29 17 28 10  7]
 [27 24 13 24 25 21]
 [14 11  3 12 12  7]]


In [14]:
x>20

array([[False,  True, False, False, False,  True],
       [ True, False, False,  True, False,  True],
       [False,  True,  True,  True, False, False],
       [False,  True, False, False, False,  True],
       [False, False,  True, False, False, False]])

In [15]:
bool_arr=x>20

In [16]:
bool_arr

array([[False,  True, False, False, False,  True],
       [ True, False, False,  True, False,  True],
       [False,  True,  True,  True, False, False],
       [False,  True, False, False, False,  True],
       [False, False,  True, False, False, False]])

In [19]:
ans=x[x>20]
print(ans)

[23 23 23 23 23 24 29 23 28 29 23]


In [57]:
b=x
print(b)

[[ 2  4 14 12  3 22]
 [ 1  3 10 27 16 17]
 [22 27  6  2  8 11]
 [20 13 21 20 17 18]
 [12  4 26  0 22  9]]


In [58]:
#for all value
b[b>20]=100
print(b)

[[  2   4  14  12   3 100]
 [  1   3  10 100  16  17]
 [100 100   6   2   8  11]
 [ 20  13 100  20  17  18]
 [ 12   4 100   0 100   9]]


In [59]:
print(b)

[[  2   4  14  12   3 100]
 [  1   3  10 100  16  17]
 [100 100   6   2   8  11]
 [ 20  13 100  20  17  18]
 [ 12   4 100   0 100   9]]


In [60]:
#For specific column in 2D array
bool_arr=b[:,3]==100
print(bool_arr)

[False  True False False False]


In [61]:
b[bool_arr,3]=99
print(b)

[[  2   4  14  12   3 100]
 [  1   3  10  99  16  17]
 [100 100   6   2   8  11]
 [ 20  13 100  20  17  18]
 [ 12   4 100   0 100   9]]


In [62]:
l= [[21,20,19,18,17],[16,15 ,14, 13, 12],[11,10,9,8,7],[6,5,4,3,2]]
arr=np.array(l)
print(arr)
print()
print("Reverse the array:- ")
print(arr[::-1])

[[21 20 19 18 17]
 [16 15 14 13 12]
 [11 10  9  8  7]
 [ 6  5  4  3  2]]

Reverse the array:- 
[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]


In [63]:
print(b)

[[  2   4  14  12   3 100]
 [  1   3  10  99  16  17]
 [100 100   6   2   8  11]
 [ 20  13 100  20  17  18]
 [ 12   4 100   0 100   9]]


In [64]:
#for column Wise
bool_arr=b[:,1]==100
print(bool_arr)

b[bool_arr,1]=0
print(b)

[False False  True False False]
[[  2   4  14  12   3 100]
 [  1   3  10  99  16  17]
 [100   0   6   2   8  11]
 [ 20  13 100  20  17  18]
 [ 12   4 100   0 100   9]]


In [65]:
#For row Wise
bool_arr=b[1,:]==100
print(bool_arr)

b[1,bool_arr]=0
print(b)

[False False False False False False]
[[  2   4  14  12   3 100]
 [  1   3  10  99  16  17]
 [100   0   6   2   8  11]
 [ 20  13 100  20  17  18]
 [ 12   4 100   0 100   9]]


In [66]:
bool_arr=b[2:,:3]==100
print(bool_arr)

[[ True False False]
 [False False  True]
 [False False  True]]


In [68]:
print(b)

[[  2   4  14  12   3 100]
 [  1   3  10  99  16  17]
 [100   0   6   2   8  11]
 [ 20  13 100  20  17  18]
 [ 12   4 100   0 100   9]]


# Broadcasting 

In [70]:
x=np.random.randint(1,10,(2,3))
y=np.random.randint(1,10,(3,2))

In [71]:
x

array([[1, 8, 3],
       [6, 9, 5]])

In [72]:
y

array([[3, 6],
       [2, 8],
       [4, 7]])

In [73]:
x+y

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [77]:
a=np.array([1,3,1])
a

array([1, 3, 1])

In [78]:
x+a

array([[ 2, 11,  4],
       [ 7, 12,  6]])

In [80]:
b=np.random.randint(1,10,(3,1))
b

array([[3],
       [4],
       [1]])

In [83]:
print(y)

[[3 6]
 [2 8]
 [4 7]]


In [84]:
y+b

array([[ 6,  9],
       [ 6, 12],
       [ 5,  8]])

In [92]:
a=np.random.randint(1,10,(2,3))
b=np.random.randint(1,10,(3,2))

In [93]:
a

array([[2, 4, 8],
       [7, 2, 1]])

In [94]:
b

array([[9, 2],
       [3, 5],
       [5, 3]])

In [95]:
b=np.transpose(b)
ans=a+b
print(ans)

[[11  7 13]
 [ 9  7  4]]


In [96]:
a

array([[2, 4, 8],
       [7, 2, 1]])

In [97]:
b

array([[9, 3, 5],
       [2, 5, 3]])

In [109]:
a=np.random.randint(1,10,(2,3))
b=np.random.randint(1,10,(3,2))

In [106]:
a

array([[3, 7, 2],
       [1, 2, 4]])

In [107]:
b

array([[1, 6],
       [8, 4],
       [3, 2]])

In [103]:
b=np.resize(b,(3,5))

In [104]:
b

array([[6, 1, 7, 9, 8],
       [5, 6, 1, 7, 9],
       [8, 5, 6, 1, 7]])

In [108]:
b=np.reshape(b,(3,2))
b

array([[1, 6],
       [8, 4],
       [3, 2]])

In [111]:
a=np.random.randint(1,10,(3,1))
b=np.random.randint(1,10,(3,3))

In [112]:
a

array([[6],
       [1],
       [5]])

In [113]:
b

array([[4, 6, 7],
       [9, 3, 1],
       [4, 2, 4]])

In [114]:
a+b

array([[10, 12, 13],
       [10,  4,  2],
       [ 9,  7,  9]])

In [115]:
a=np.random.randint(1,10,(1,3))
b=np.random.randint(1,10,(3,1))

In [116]:
a

array([[6, 4, 9]])

In [117]:
b

array([[2],
       [9],
       [9]])

In [118]:
a+b

array([[ 8,  6, 11],
       [15, 13, 18],
       [15, 13, 18]])

In [119]:
a=np.random.randint(1,10,(1,3))
b=np.random.randint(1,10,(1,1))

In [120]:
a

array([[6, 8, 5]])

In [121]:
b

array([[5]])

In [122]:
a+b

array([[11, 13, 10]])

# Examples With Files

In [19]:
#Killed and Wounded in India
import numpy as np
import csv

with open('year2017.csv','r') as file_obj:
    file_data=csv.DictReader(file_obj,skipinitialspace=True)
    
    killed=[]
    wounded=[]
    country=[]
    for row in file_data:
        killed.append(row['Killed'])
        country.append(row['Country'])
        wounded.append(row['Wounded'])

np_killed=np.array(killed)
np_wounded=np.array(wounded)
np_country=np.array(country)

np_killed[np_killed=='']='0.0'
np_wounded[np_wounded=='']='0.0'

np_killed=np.array(np_killed,dtype=float)
np_wounded=np.array(np_wounded,dtype=float)

killed_wounded=np_killed+np_wounded

bool_arr=np_country=='India'
ans=killed_wounded[bool_arr]
print(ans.sum())
print(killed_wounded.sum())

1167.0
51372.0


In [46]:
#Killed In USA

import numpy as np
import csv

with open('terrorismData.csv',encoding='utf-8') as file_obj:
    data=csv.DictReader(file_obj,skipinitialspace=True)
    
    killed=[]
    country=[]
    for row in data:
        killed.append(row['Killed'])
        country.append(row['Country'])
    
np_killed=np.array(killed)
np_country=np.array(country)

np_killed[np_killed=='']='0.0'

np_killed=np.array(np_killed,dtype=float)

bool_arr=np_country=='United States'
ans=np_killed[bool_arr]

print(ans.sum())

3771.0


In [45]:
# Find the number of attack held between day 10 and day 20?(ignoring the year and month)(including both day)
import numpy as np
import csv

with open('terrorismData.csv',encoding='utf-8') as file_obj:
    data=csv.DictReader(file_obj,skipinitialspace=True)
    
    day=[]
    for row in data:
        day.append(row['Day'])

np_day=np.array(day)
np_day=np.array(np_day,dtype=float)
new_np_day=np_day[(np_day>=10) & (np_day<=20)]
count=0
for i in new_np_day:
    count+=1
print(count)

66330


In [44]:
# Find the number of attack held between 1 Jan 2010 and 31 Jan 2010?(including both date).
## Open and read data file as specified in the question
## Print the required output in given format
# Find the number of attack held between 1 Jan 2010 and 31 Jan 2010?(including both date).
import numpy as np
import csv

with open('terrorismData.csv',encoding='utf-8') as file_obj:
    data=csv.DictReader(file_obj,skipinitialspace=True)
    
    day=[]
    year=[]
    month=[]
    for row in data:
        day.append(row['Day'])
        month.append(row['Month'])
        year.append(row['Year'])

np_day=np.array(day)
np_month=np.array(month)
np_year=np.array(year)
np_day=np.array(np_day,dtype=float)
np_month=np.array(np_month,dtype=float)
np_year=np.array(np_year,dtype=float)
new_np_day=np_day[(np_day>=1) & (np_day<=31) & (np_month==1) & (np_year==2010)]
print(len(new_np_day))

271


In [39]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np
import csv

with open('terrorismData.csv',encoding='utf-8') as file_obj:
    file_data=csv.DictReader(file_obj,skipinitialspace=True)
    
    killed=[]
    wounded=[]
    city=[]
    attack_group=[]
    month=[]
    year=[]
    state=[]
    for row in file_data:
        if row['City']!='Unknown' and row['Group']!='Unknown':
            killed.append(row['Killed'])
            wounded.append(row['Wounded'])
            city.append(row['City'])
            attack_group.append(row['Group'])
            month.append(row['Month'])
            year.append(row['Year'])
            state.append(row['State'])

np_killed=np.array(killed)
np_wounded=np.array(wounded)
np_city=np.array(city)
np_group=np.array(attack_group)
np_month=np.array(month)
np_year=np.array(year)
np_state=np.array(state)

np_killed[np_killed=='']='0.0'
np_wounded[np_wounded=='']='0.0'

np_killed=np.array(np_killed,dtype=float)
np_wounded=np.array(np_wounded,dtype=float)
np_year=np.array(np_year,dtype=float)
np_month=np.array(np_month,dtype=float)
np_year=np.array(np_year,dtype=int)
np_month=np.array(np_month,dtype=int)

casuality=np_killed+np_wounded
casuality=np.array(casuality,dtype=int)
casuality=casuality[(np_month>=5) & (np_month<=7) & (np_year==1999) & (np_state=='Jammu and Kashmir')]
np_city=np_city[(np_month>=5) & (np_month<=7) & (np_year==1999) & (np_state=='Jammu and Kashmir')]
np_group=np_group[(np_month>=5) & (np_month<=7) & (np_year==1999) & (np_state=='Jammu and Kashmir')]

max_casuality=casuality.max()
ind=np.where(casuality==max_casuality)

city_anss=np_city[ind[0][0]]
group_anss=np_group[ind[0][0]]

print(max_casuality,city_anss,group_anss)

22 Kargil District Separatists


In [67]:
#Find the casualty in the Red Corridor States ? Mainly Red corridor states include Jharkhand, Odisha, Andhra Pradesh, and Chhattisgarh.
#Note: Casualty=Killed +Wounded
#Print count of Casualty as integer value

import numpy as np
import csv

with open('terrorismData.csv',encoding='utf-8') as file_obj:
    file_data=csv.DictReader(file_obj,skipinitialspace=True)
    
    killed=[]
    wounded=[]
    state=[]
    for row in file_data:
        if row['State']=='Jharkhand' or row['State']=='Odisha' or row['State']=='Andhra Pradesh'or row['State']=='Chhattisgarh':
            killed.append(row['Killed'])
            wounded.append(row['Wounded'])
            state.append(row['State'])
            
np_killed=np.array(killed)
np_wounded=np.array(wounded)
np_state=np.array(state)

np_killed[np_killed=='']='0.0'
np_wounded[np_wounded=='']='0.0'

np_killed=np.array(np_killed,dtype=float)
np_wounded=np.array(np_wounded,dtype=float)
np_killed=np.array(np_killed,dtype=int)
np_wounded=np.array(np_wounded,dtype=int)

casuality=np_killed+np_wounded
print(casuality.sum())

5628


In [74]:
import numpy as np
import csv
from collections import Counter


with open('terrorismData.csv',encoding='utf-8') as file_obj:
    file_data=csv.DictReader(file_obj,skipinitialspace=True)
    
    killed=[]
    wounded=[]
    city=[]
    for row in file_data:
        if row['Country']=='India':
            if row['City']!='Unknown':
                killed.append(row['Killed'])
                wounded.append(row['Wounded'])
                city.append(row['City'])
            
np_killed=np.array(killed)
np_wounded=np.array(wounded)
np_city=np.array(city)

np_killed[np_killed=='']='0.0'
np_wounded[np_wounded=='']='0.0'

np_killed=np.array(np_killed,dtype=float)
np_wounded=np.array(np_wounded,dtype=float)
np_killed=np.array(np_killed,dtype=int)
np_wounded=np.array(np_wounded,dtype=int)

casuality=np_killed+np_wounded
d={}
for i in range(len(np_city)):
    if np_city[i] in d:
        d[np_city[i]]+=casuality[i]
    else:
        d[np_city[i]]=casuality[i]
top_city=dict(Counter(d).most_common(5))
for i in top_city:
    print(i,top_city[i])

Srinagar 3134
New Delhi 2095
Mumbai 2016
Jammu 1119
Guwahati 822


In [86]:
import numpy as np
import csv
from collections import Counter


with open('terrorismData.csv',encoding='utf-8') as file_obj:
    file_data=csv.DictReader(file_obj,skipinitialspace=True)
    
    day=[]
    for row in file_data:
        day.append(row['Day'])

np_days=np.array(day,dtype=int)
np_day=np.unique(np_days)

d={}
for i in np_days:
    if i in d:
        d[i]=d[i]+1
    else:
        d[i]=1
maxx=0
for i in d:
    if d[i]>maxx:
        maxx=d[i]
for i in d:
    if d[i]==maxx:
        print(i,maxx)
        break

15 6500


In [93]:
import numpy as np
import csv
from collections import Counter


with open('terrorismData.csv',encoding='utf-8') as file_obj:
    file_data=csv.DictReader(file_obj,skipinitialspace=True)
    
    day=[]
    for row in file_data:
        day.append(row['Day'])

np_days=np.array(day,dtype=int)
np_day,count=np.unique(np_days,return_counts=True)
print(np_day[np.argmax(count)],count[np.argmax(count)])


15 6500
